$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: CLI_5b_env_registered
description: Pipeline job with component using a registered AzureML environment

jobs:
  hello_python_world_job:
    type: command
    component: file:./component.yml
    compute: azureml:cpu-cluster

